ModelName: simple_lstm
SearchMethod: grid_search_params
ParameterSpecification:
    num_hidden_units:
        InterpretAs: value_list
        Values: [2, 4]
    batch_size:
        InterpretAs: value_range
        Values: [8, 11, 2]
    learning_rate:
        InterpretAs: value_list
        Values: [0.001]
    epochs:
        InterpretAs: value_list
        Values: [1]
DataSubsetFraction: .005
DataDirectory: 'data/untracked/truncated_samples' 
ResultsDirectory: 'data/untracked/results'
# DATA_SUBSET_FRACTION = 1
# DATA_DIRECTORY = '/mnt/disks/ptbdb/data'
# RESULTS_DIRECTORY = '/mnt/disks/ptbdb/results/'
