DataSubsetFraction: .005
DataDirectory: '/mnt/disks/ptbdb/data'
ResultsDirectory: '/mnt/disks/ptbdb/results/testing_grid_search'
ModelName: simple_inception
##### Grid Search Specification #####
SearchMethod: grid_search_params
ParameterSpecification:
    batch_size:
        InterpretAs: value_range
        Values: [4, 7, 2]
    learning_rate:
        InterpretAs: value_list
        Values: [0.001]
    epochs:
        InterpretAs: value_list
        Values: [1]
    num_filters:
        InterpretAs: value_list
        Values: [16]
    num_layers:
        InterpretAs: value_list
        Values: [2]
    dropout_rate:
        InterpretAs: value_list
        Values: [0.5]
##### Random Search Specification #####
# SearchMethod: random_search_params
# ParameterSpecification:
#     num_hidden_units:
#         RandomizationType: integer
#         Low: 2
#         High: 4
#     batch_size:
#         RandomizationType: integer
#         Low: 2
#         High: 4
#     learning_rate:
#         RandomizationType: log_transformed
#         Low: -4
#         High: -2.5
#     epochs:
#         RandomizationType: value_list
#         Low: 1
#         High: 1
#     num_filters:
#         RandomizationType: value_list
#         Low: 64
#         High 64
#     num_layers:
#         RandomizationType: value_list
#         Low: 2
#         High: 2
