DataSubsetFraction: 1
DataDirectory: '/mnt/disks/ptbdb/data'
ResultsDirectory: '/mnt/disks/ptbdb/results/dropout_test'
ModelName: simple_inception
##### Grid Search Specification #####
SearchMethod: grid_search_params
ParameterSpecification:
    batch_size:
        InterpretAs: value_list
        Values: [50]
    learning_rate:
        InterpretAs: value_list
        Values: [0.01]
    epochs:
        InterpretAs: value_list
        Values: [25]
    num_filters:
        InterpretAs: value_list
        Values: [32, 16]
    num_layers:
        InterpretAs: value_list
        Values: [4, 2]
    dropout_rate:
        InterpretAs: value_list
        Values: [0.01, 0.33, 0.67]
