DataSubsetFraction: 1
DataDirectory: '/mnt/disks/ptbdb/data'
ResultsDirectory: '/mnt/disks/ptbdb/results/'
ModelName: simple_inception
##### Grid Search Specification #####
SearchMethod: grid_search_params
ParameterSpecification:
    batch_size:
        InterpretAs: value_list
        Values: [200, 100, 50]
    learning_rate:
        InterpretAs: value_list
        Values: [0.001]
    epochs:
        InterpretAs: value_list
        Values: [10]
    num_filters:
        InterpretAs: value_list
        Values: [64, 16, 4]
    num_layers:
        InterpretAs: value_list
        Values: [4, 2, 1]
