DataSubsetFraction: 0.005
DataSubsetFraction: 1
DataDirectory: '/mnt/disks/ptbdb/data'
ResultsDirectory: '/mnt/disks/ptbdb/results/vgg_grid_search_B'
ModelName: vgg_net
##### Grid Search Specification #####
SearchMethod: grid_search_params
ParameterSpecification:
    batch_size:
        InterpretAs: value_list
        Values: [100, 50]
    learning_rate:
        InterpretAs: value_list
        Values: [0.001]
    epochs:
        InterpretAs: value_list
        Values: [25]
    filters_base_exp:
        InterpretAs: value_list
        Values: [6, 4]
    num_convolutions_in_each_block:
        InterpretAs: value_list
        Values: 
            - [2, 2, 2]
            - [2, 2]
            - [2]
    filter_size:
        InterpretAs: value_list
        Values: [64, 16, 4]
